### ISSUE TITLE
 Where is the binary code mapping module present?

### ISSUE THREAD

**Issue by codezart** [redcping/Delta_Age_AdaIN#2]
Both the paper and the code don't have enough information on the binary code mapping (BCM) module.
Does the BCM module only take the age normalized list and train on what using MLP to get the mean (S) and standard deviation (T) lists?
@redcping  can you please provide insight on this?

Talking about the Binary code mapping module section in this image
![image](https://github.com/redcping/Delta_Age_AdaIN/assets/44206264/d1b3d010-b2d9-4f98-8d72-8a0e422bbd31)

**Comment by codezart** [comment]
It seems that the BCM module takes the ages 0 to 99 in 8 bit binary code and then normalizes it. then this single vector is passed to MLP to train on. but what is it learning on? and the input is just one single vector? How is the S and T generated from this vector?

**Comment by redcping** [comment]
> It seems that the BCM module takes the ages 0 to 99 in 8 bit binary code and then normalizes it. then this single vector is passed to MLP to train on. but what is it learning on? and the input is just one single vector? How is the S and T generated from this vector?

During training, a sample's feature is combined with S and T corresponding to 0 to 99 to predict 100 sets of age differences, which are then used to infer the age of the current sample. The DAA operation can be found in line 130 of DeltaAdaINNet.py.
