### ISSUE TITLE
请问如何预测照片中人物的年龄？

### ISSUE THREAD

**Issue by InbesLN** [redcping/Delta_Age_AdaIN#6]
按照说明建立好模型以后，请问如何利用该模型去预测其他照片中人物的年龄呢？我不是很明白

**Comment by redcping** [comment]
通过网络训练，二进制映射能够捕捉并表示与特定年龄特征相对应的均值和标准差。将100组均值和标准差与当前特征进行DAA操作即可获取100组特征差异，随后这些特征差异被解码成相应的年龄差异。因此，我们相当于预测了当前人像与1至100岁之间每个年龄的差别。通过这种方式，我们可以为当前人像得到100组不同的年龄预测结果。将这些预测结果的平均值，我们可以得到一个更为准确的年龄估计。
